### ISSUE TITLE
QUESTION: ENABLE_DHCP - Is there a way to start DHCP server for selected network interfaces ONLY ?

### ISSUE THREAD

**Issue by ramukima** [BBVA/kvm#22]
I have two interfaces to the VM and I want DHCP service to be run only for one of those interfaces.

**Comment by methadata** [comment]
You should be able to provide custom configurations to `dnsmasq` service in the container by means of the `DNSMASQ_OPTS` env variable. Take a look at the [dnsmasq man page](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html). There you'd probably find useful the `--except-interface` and `--listen-address` options.

I will close this issue now. Feel free to reopen it if the provided solution does not fit your environment and/or use case. If so, and in order to understand better the use case involved here, please describe it as much as possible.

The aim to implement the `ENABLE_DHCP` flag is only to disable the `dnsmasq` service in the container if not used.
